### ISSUE TITLE
Consolidate display logic for FAQ and Topic markup throughout the plugin

### ISSUE THREAD

**Issue by cjg89** [UCF/UCF-FAQ-CPT#18]
We have a lot of similar/identical display logic for printing markup like FAQ CTA footers, Related FAQs, etc. that should be consolidated into reusable functions.

**Comment by rjucf** [comment]
Resolved with https://github.com/UCF/UCF-FAQ-CPT/commit/01f181b31ada609df75b8c093465f4a6e2e9a274
