### ISSUE TITLE
UCF_FAQ_Common::get_related_faqs_by_topic() throws warnings when no related FAQs are set

### ISSUE THREAD

**Issue by cjg89** [UCF/UCF-FAQ-CPT#32]
`Warning: array_merge(): Argument #2 is not an array in /common/ucf-faq-list-common.php on line 214`

`Warning: array_filter() expects parameter 1 to be array, null given in /common/ucf-faq-list-common.php on line 223 `

https://github.com/UCF/UCF-FAQ-CPT/blob/master/common/ucf-faq-list-common.php#L212-L223

Need to ensure `$related` actually returns an array before attempting to merge it into `$retval`.

**Comment by rjucf** [comment]
Fixed in v1.0.1
