### ISSUE TITLE
Typeaheadjs and handlebarjs missing on ucf_faq_scripts

### ISSUE THREAD

**Issue by vinhtvu2** [UCF/UCF-FAQ-CPT#64]
![image](https://user-images.githubusercontent.com/10465389/90653808-a477fa80-e20d-11ea-9a2a-d9430e442a6f.png)

**Comment by cjg89** [comment]
I think the main issue here is that, if the typeahead/handlebars scripts are set to _not_ enqueue via plugin options, and custom script alternatives are not provided, the main plugin js file is still registered with those scripts set as dependencies--hence the error in the screenshot above.

https://github.com/UCF/UCF-FAQ-CPT/blob/32168fa03080fc50e5a0551a81798950f3940dc2/common/ucf-faq-list-common.php#L297-L311

I think we should ideally not append the typeahead and handlebars handles to `$dependencies` if they are empty strings--and make it more obvious with field descriptions for the handle values that making said values empty will prevent the scripts from registering at all.

**Comment by cjg89** [comment]
Closing this issue; this should be resolved as of v2.0.0.
